# permissions for end users to edit dlexperiments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dlexperiment-editor-role
rules:
- apiGroups:
  - mlhub.njuics.cn
  resources:
  - dlexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlhub.njuics.cn
  resources:
  - dlexperiments/status
  verbs:
  - get
